config/urls.py
from users import urls
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static #It helps us serve static file.

urlpatterns = [
    path("",include("core.urls",namespace="")),
    path("events/",include("events.urls",namespace="events")),
    path("users/",include("users.urls",namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from events import views as event_views
from . import views
app_name = "core"

urlpatterns =[
    path("",views.home_view,name="home"),
    path("events/",event_views.EventView.as_view(),name="event"),
    path("abutus/",views.aboutus, name="aboutus")
    ]

events/urls.py
from events.forms import CreateEventForm
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
path("create/",views.CreateEventView.as_view(),name="create"),
path("<int:pk>",views.event_detail,name="event_detail"),
path("<int:pk>/edit",views.EditEventView.as_view(),name="edit"),
path("<int:pk>/photos/",views.EventPhotosView.as_view(),name="photos"),
path("<int:pk>/photos/add",views.AddPhotoView.as_view(),name="add-photo"),
path("<int:event_pk>/photos/<int:photo_pk>/delete/",views.delete_photo,name="delete-photo"),
path("<int:event_pk>/photos/<int:photo_pk>/edit/",views.EditPhotoView.as_view(),name="edit-photo"),
path("search/",views.search,name="search"),
path("approve/<int:pk>", views.approve, name = "approve"),
]

lists/urls.py
from django.urls import path
from django.urls import path
from . import views
app_name = "lists"

urlpatterns = [
    path("toggle/<int:event_pk>",views.toggle_event,name="toggle-event"),
    path("favs/",views.SeeFavView.as_view(),name="see-favs"),
]

users/urls.py
from django.urls import path 
from . import views

app_name = "users"

urlpatterns = [
    path("login/",views.LoginView.as_view(),name="login"),
    path("login/github/",views.github_login,name="github-login"),
    path("login/github/callback/",views.github_callback,name="github-callback"),
    path("logout/",views.log_out,name="logout"),
    path("signup/",views.SignUpView.as_view(),name="signup"),
    path("verify/<str:key>/",views.complete_verification,name="complete-verification"),
    path("update-profile",views.UpdateProfileView.as_view(),name="update"),
    path("update-password",views.UpdatePasswordView.as_view(),name="password"),
    path("<int:pk>/",views.UserProfileView.as_view(),name="profile"),
]

templates/partials/event_card.html
{%comment%}
<h3>
    <a href="{% url " events:event_detail" event.pk %}">
        <!-- <img src="{{event.first_photo}}" /> -->
        {{event.name}}
    </a>
</h3>
{%endcomment%}

{% load static %}

<style>
    body{
    background-color: #FFFFFF;
    position: relative;
    overflow-x: hidden;
    }

    .events {
        padding-top: 80px;
        padding-left: 0%;
        margin-left: 0px;

        /* padding-right: 100px; */
    }

    .row1 {
        padding-top: 5%;
        margin-left: 40px;
    }

    .topic-events{
      text-align:center;
    }

    /* .events-list{
      padding-left: ;
      position: relative;
    } */

    .card {
        border-radius: 10px;
        border: 1px solid black;
        /* background-color: #3686DA; */
        color: white;
        width: 19rem;
        min-height:500px;
        transition: 0.5s ease;
        cursor: pointer;
        box-shadow: -10px 30px 20px rgba(0, 0, 0, 0.0);
    }

    .card:hover {
        transform: scale(1.03);
        box-shadow: -20px 30px 20px rgba(0, 0, 0, 0.3);
    }

    .event-date {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        border-radius: 100%;
        background-color: #E3E0DF;
        height: 100px;
        width: 100px;
        position: absolute;
        left: 30%;
        /* bottom: 50%; */
        top: 140px;
        color: black;
        box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.2);
    }

     .event-date-text {
        /* position: absolute; */
        /* left: 33%;
        bottom: 30%; */
        margin-top: 30px;
    }

    .event-date-text-year {
        /* position: absolute; */
        /* left: 20%;
        bottom: 10%; */
        transform: translateY(-10px);
    } 

    .card-title {
        font-size: 20px;
        text-decoration: none;
        text-decoration-color: white;
        padding-top: 15%;
    }

    .card-title:hover {
        color:#419CD6;
    }

    .verified {
        position: absolute;
        margin-left: 15px;
    }

    .learn {
        float: right;
        text-decoration: none;
        color: black;
    }

    .learn:hover {
        color: #419CD6;;
    }

    .rating {
        transform: scale(1.2);

        position: absolute;
        left: 28px;
    }

    .rating-star {
        position: relative;
        bottom: 3px;
        right: 5px;
    }

    /*next- page*/

    .next-event {
        text-align: center;
        line-height: 5;
        margin-top: 2%;
        margin-bottom: 100px;
    }

    .text {
   overflow: hidden;
   text-overflow: ellipsis;
   display: -webkit-box;
   -webkit-line-clamp: 2; /* number of lines to show */
   -webkit-box-orient: vertical;
}
    .text-limit-description{
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 5; /* number of lines to show */
        -webkit-box-orient: vertical;

    }


    @media screen and (max-width: 1000px) {
        .card {
            margin-bottom: 40px;
        }
    }

    @media screen and (min-width: 1200px) and (max-width: 1250px) {
        .card {
            transform: scale(0.8);
        }

        .card:hover {
            transform: scale(0.9);
        }

        .row1 {
            margin-left: -30px;
        }

    }

    @media screen and (min-width: 992px) and (max-width: 1200px) {
        .card {
            transform: scale(0.7);
        }

        .card:hover {
            transform: scale(0.75);
        }

        .row1 {
            margin-left: -60px;
        }

    }

    @media screen and (max-width: 992px) {
        .row1 {
            position: relative;
            left: 5%;
        }
    }

    @media screen and (min-width: 600px) and (max-width: 767px) {
        .row1 {
            position: relative;
            left: 25%;
        }
    }

    @media screen and (max-width: 600px) {
        .row1 {
            position: relative;
            left: 13%;
        }
    }

    .bottomleft {
        position: absolute;

        bottom: 0;
        left: 0;
        z-index: -1
    }

    .topright {
        position: absolute;

        top: 150px;
        right: 0;
        z-index: -1;

    }


    @media screen and (max-width: 740px) {
        span {
            color: white;
        }

    }
</style>

{% if forloop.counter == 1 %}
<img class="bottomleft" src="{% static 'images/event/bottomleft.svg' %}" alt="">
<img class="topright" src="{% static 'images/event/topright.svg' %}" alt="">
<div class="container-fluid events">
    <!-- <h1 class="topic-events">Events</h1> -->
{% endif %}

{% if  forloop.counter == 1 %}
    <div class="row row1">
    {% endif %}

    {% if  forloop.counter == 5 %}
    <div class="row row1">
    {% endif %}

        <div class="col-lg-3 col-md-6 events-list">
            <a href="{% url "events:event_detail" event.pk %}" style="text-decoration: none; color:black">
            <div class="card">
                {% if event.first_photo %}
                    <img style="border-top-left-radius: 10px; border-top-right-radius: 10px; height: 200px;" src="{{event.first_photo}}" class="card-img-top" alt="Update your Photo from Update Events">
                {% else %}
                    <div style="background-color: darkslategray; height:200px; border-top-left-radius: 10px; border-top-right-radius: 10px; position:relative">
                        <h5 style="
                            text-align: center;
                            color:whitesmoke; 
                            position: relative;
                            top:50%;
                            transform: translateY(-50%);
                        ">
                            {{event.name}} <br>
                            <p style="font-size: 9px; color:whitesmoke">Upload images from Edit Events</p>
                        </h5>
                        
                    </div>
                {% endif %}
                <div class="card-body">
                    <div class="event-date">
                        <p class="event-date-text"><b> {{event.event_date|date:"M"}}</b></p>
                        <p class="event-date-text-year">{{event.event_date|date:"W-Y"}}</p>

                    </div>
                    {% if event.organizer.superorganizer %}
                    <img class="verified" src="{%static 'images/event/verified.svg' %}">
                    {% endif %}
                    <h5 class="card-title text">
                        {{event.name}}
                    </h5>
                    <hr>
                    <!-- <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pharetra pulvinar ac
                        tincidunt id nisi, libero. Turpis amet, sodales cras ornare non adipiscing. Fusce nec sed ipsu
                    </p> -->
                    <p class="card-text text-limit-description">
                        {{event.description}}
                    </p>
                    <p class="rating"><img class="rating-star" src="{%static 'images/event/star.svg' %}">{{event.total_rating}}</p>

                        <a class="learn" href="{% url "events:event_detail" event.pk %}">Learn more
                            <img src="{%static 'images/event/arrow.svg'%}" alt=""></a>
                </div>
            </div>
            </a>

        </div>
        {% if  forloop.counter == 4 %}
        </div>
        {% endif %}
        {% if  forloop.counter == 8%}
        </div>
        {% endif %}
    {% if forloop.counter == 8 %}
    </div>
    {% endif %}

templates/partials/footer.html
<!-- <footer>
    &copy; Eventhub
</footer> -->
<style>
    footer{
  color:white;
  background-color: black;
  text-align: center;
  margin-top: 10px;
  padding-top: 1.2%;
  padding-bottom: 1%;
}
.foot-icon{
  padding-left: 5px;
  padding-right: 5px;
  opacity: 0.8;
}

</style>

<footer>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4">
          <p>@2021. All rights reserved.</p>
        </div>
        <div class="col-md-4">
          <p><strong>Eventhub</strong></p>
        </div>
        <div class="col-md-4">
          <i class="fab fa-instagram foot-icon"></i>
          <i class="fab fa-facebook-f foot-icon"></i>
          <i class="fab fa-twitter foot-icon"></i>
          <i class="fab fa-youtube foot-icon"></i>
        </div>
      </div>
    
    </div>
    </footer>

templates/partials/messages.html
{% if messages %}
<style>
    .message{
        display: flex;
        margin-left: 42%;
        margin-top: 50px;
        padding: 10px;
        padding-left: 20px;
        padding-right: 20px;
        position: absolute;
        background-color: dodgerblue;
        border-radius: 15px;
        top: 20px;
        z-index: 1000000;
        font-size: 20px;
        color: white;
        
    }
    @keyframes messageFadeIn{
        0%{
            opacity: 0;
            transform: translateY(-80px);
        }
        10%{
            opacity: 1;
            transform: translateY(0px);
        }
        90%{
            opacity: 1;
            transform: translateY(0px);
        }
        100%{
            opacity: 0;
            transform: translateY(-80px);
        }
    }
    .message{
        animation: messageFadeIn 5s ease-in-out forwards;
    }
</style>
    <div class="messages">
        {% for message in messages %}
            <span class="message{% if message.tags %} {{message.tags }}{% endif %}"><b>{{message}}</b></span>
        {% endfor %}
    </div>
{% endif %}

templates/partials/nav.html
{%comment%}
<a href="{% url "core:event" %}">Eventhub</a>
<ul>
    {% if user.is_authenticated %}
    <li><a href="{% url "users:logout" %}">Log out</a></li>
    {% else %}
    <li><a href="{% url "users:login" %}">Login</a></li>
    <li><a href="{% url "users:signup" %}">Sign up</a></li>
    {% endif %}

</ul>
{% endcomment %}
{% load static %}

{% if user.is_authenticated %}
<style>
    .navbar {

        background-color: #FEFFEC;
        position: fixed;
        width: 100%;
        z-index: 1000;
    }

    .navbar-nav {
        margin-right: 50px;
    }

    .navbar-brand {
        font-size: 25px;
    }

    .navbar-brand:hover {
        color:cornflowerblue;
    }

    .navbar-logo-img {
        margin-right: 10px;
        margin-left: 20px;
        opacity: 0.8;
    }

    .nav-item {
        margin-left: 5px;
    }

    .nav-item-nv {
        border-radius: 20px;
        padding:7px;
        text-decoration:none;
    }
    .nav-item-nv:hover {
        background-color: cornflowerblue;
    }

    .search {
        margin-right: 5px;
    }

    @media screen and (max-width: 992px) {
        .search {
            width: 300px;
        }
    }

    .navbar-profile-img {
        margin-right: 5px;
        margin-left: 10px;
        opacity: 0.8;
        height: 10px;
        width: 10px;
    }

    .navbar-profile-img:hover {
        opacity: 1;
    }

    .topic-events {
        margin-left: 3%;
        font-size: 5rem;
        z-index: 1000;
    }

    .dropdown .dropbtn {
        font-size: 16px;
        border: none;
        outline: none;
        padding: 10px 16px;
        background-color: inherit;
        font-family: inherit;
        /* Important for vertical align on mobile phones */
        margin: 0;
        /* Important for vertical align on mobile phones */
    }

    /* Dropdown content (hidden by default) */
    .dropdown-content {
        display: none;
        position: absolute;
        background-color: cornflowerblue;
        min-width: 100px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 1;
    }

    /* Links inside the dropdown */
    .dropdown-content a {
        color:white;
        float: none;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        text-align: left;
        opacity: 0.8;
    }

    /* Show the dropdown menu on hover */
    .dropdown:hover .dropdown-content {
        display: block;
    }

    .get:hover {
        font-weight: bold;
        font-weight: 17px;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light ">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url "core:event" %}"><img class="navbar-logo-img" src="{% static 'images/event/favicon1.svg'%}" alt="" width="55"
                height="46">EVENTHUB</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 ">
                <form class="search d-flex" method="get" action="{% url 'events:search' %}">
                    <input class="form-control me-2" name="city" placeholder="Search by city" aria-label="Search"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <li class="nav-item">
                    <a class="nav-item-nv nav-item-nv-aboutus nav-link " href="{% url 'events:create' %}">Create Event</a>
                <!-- <form class=" search d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search by City" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form> -->
                
                <li class="nav-item">
                    <a class="nav-item-nv nav-item-nv-aboutus nav-link " href="{% url 'lists:see-favs' %}">Favourite</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item-nv nav-item-nv-events nav-link " href="{% url "core:event" %}">View Events</a>
                </li>
                <li class="nav-item nav-item-1">
                    <a class="nav-item-nv nav-link" href="{% url "core:aboutus" %}">About us</a>
                </li>

                <li class="nav-item">
                    <a class="navbar-profile-img" href="{{user.get_absolute_url}}">
                        {% if user.avatar %}
                            <img style="border-radius: 50%; z-index: 10000;" src="{{user.avatar.url}}" alt="{{user.first_name}}'s avatar" width="40px" height="40px">
                        {% else %}
                        <img src="{% static 'images/event/profile.svg' %}" alt="" width="40px"
                            height="auto">
                        {% endif %}
                        </a>
                        </li>
                <li>
                    <div class="dropdown">
                        <button class="dropbtn">
                            <i class="fas fa-caret-down"></i>
                        </button>
                        <div class="dropdown-content">
                            <a class="get" href="" %}">Hello {{user.first_name}}</a>
                            <a class="get" href="{% url "users:logout" %}">Log out</a>
                        </div>
                    </div>

                </li>


            </ul>

        </div>
    </div>
</nav>

{% else %}
<style>
    .navbar {
        z-index: 1000;
        background-color: #FEFFEC;
        position:fixed;
        width: 100%;
    }

    .navbar-nav {
        margin-right: 50px;
    }

    .navbar-brand {
        font-size: 25px;
    }

    .navbar-brand:hover {
        font-weight: bold;

    }

    .navbar-logo-img {
        margin-right: 10px;
        margin-left: 20px;
        opacity: 0.8;
    }

    .nav-item-1:hover,
    .nav-item-2:hover {
        margin-left: -4px;
    }

    .nav-item-3:hover {
        margin-left: -3px;
    }

    .btn-nav {
        background-color: #6b6bff;

        color: white;
        border-radius: 14px;
        border: none;
        padding: 0;

        width: 5rem;
        height: 2rem;
        margin-top: 4px;
        margin-left: 8px;
    }

    .btn-nav:hover {
        position: relative;

        background-color: blue;
        font-weight: bold;
        width: 5.3rem;
        left: 3px;
        margin-left: 3px;
    }

    @media only screen and (max-width: 990px) {
        .btn-nav {
            margin-left: 0;

        }

        .btn-nav:hover {
            left: -3px;
        }
    }

    .nav-item-nv:hover {

        font-weight: bold;
        font-size: 16px;
        /* font-size: 17px; */
        margin-left: 0px;

    }

    .introduction {
        background-color: rgba(133, 206, 222, 0.3);
    }

    .intro-img {
        width: 50%;
        margin-top: 80px;
        margin-bottom: 60px;
    }

    .intro-text {
        margin-top: 180px;
        margin-left: 150px;
        margin-bottom: 50px;
    }

    @media only screen and (max-width: 767px) {
        .intro-text {
            position: relative;
            right: 60px;
            bottom: 130px;
        }
    }

    .btn-intro {
        background-color: #6b6bff;

        color: white;
        border-radius: 14px;
        border: none;



        width: 8rem;
        height: 3.5rem;
        margin-top: 50px;

    }

    .btn-intro:hover {
        position: relative;
        right: 8px;
        background-color: blue;
        font-weight: bold;
        width: 9rem;


    }

    @media only screen and (max-width: 765px) {
        .introduction {
            text-align: center;
        }

        .intro-img {
            width: 100%;
        }
    }
</style>

<nav class="navbar navbar-expand-lg navbar-light ">
    <div class="container-fluid">

        <a class="navbar-brand" href="{% url "core:home" %}"><img class="navbar-logo-img"
                src="{%static 'images/homepage/favicon1.svg' %}" alt="" width="55" height="46">EVENTHUB</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 ">

                <li class="nav-item nav-item-1">
                    <a class="nav-item-nv nav-link " href="{% url "core:aboutus" %}">About us</a>
                </li>
                <li class="nav-item nav-item-2">
                    <a class="nav-item-nv nav-link " href="{% url "core:event" %}">Events</a>
                </li>
                <li class="nav-item nav-item-3">
                    <a class="nav-item-nv nav-link" href="{% url "users:signup" %}">JOIN</a>
                </li>
                <li class="nav-item">
                    <form method="get" action="/users/login">
                        <button class="btn-nav" type="submit">LOG IN</button>
                    </form>
                </li>


            </ul>

        </div>
    </div>
</nav>
{% endif %}

templates/partials/social_login.html
{% comment %}
<div>
    <a>
        Continue with Google
    </a>
    <a  href="{% url 'users:github-login' %}">
        Continue with Github
    </a>
</div>
{%endcomment%}
<style>
    .github{
        margin-bottom: 15px;
    }
    .github-button:hover{
        transform: translateY(1px);
    }
    .github-button:focus{
        transform: translateY(-1px);
    }
    .seperator{
        display: flex;
        flex-flow:row;
        font-size: larger;
        justify-content: center;
        align-items: center;
        vertical-align: center;
        margin-bottom: 10px;
    }
</style>
<div class="github">
    <a href="{% url 'users:github-login' %}">
        <button class="btn github-button" style="background-color: #419CD6; width:25rem; border-radius: 10px;" type="submit">
            <span style="font-size: 15px; vertical-align: center; color: white;">
                <i class="fab fa-github fa-1x" style="margin-right: 5px;"></i>
                Continue with Github
            </span>
        </button>
    </a>
</div>
<div class="seperator">
    <hr width="110px" style="display: inline-block; margin-right: 20px;">
    <b>OR</b>
    <hr width="110px" style="display: inline-block; margin-left: 20px;">
</div>