config/urls.py
from users import urls
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static #It helps us serve static file.

urlpatterns = [
    path("",include("core.urls",namespace="")),
    path("events/",include("events.urls",namespace="events")),
    path("users/",include("users.urls",namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views
app_name = "conversations"

urlpatterns = [
    path("go/<int:organizer_pk>/<int:participants_pk>/",views.go_conversation,name="go"),
    path("<int:pk>/",views.ConversationDetailView.as_view(),name="detail")
]

core/urls.py
from django.urls import path
from events import views as event_views
from . import views
app_name = "core"

urlpatterns =[
    path("",views.home_view,name="home"),
    path("events/",event_views.EventView.as_view(),name="event"),
    path("abutus/",views.aboutus, name="aboutus")
    ]

events/urls.py
from events.forms import CreateEventForm
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
path("create/",views.CreateEventView.as_view(),name="create"),
path("<int:pk>",views.event_detail,name="event_detail"),
path("<int:pk>/edit",views.EditEventView.as_view(),name="edit"),
path("<int:pk>/photos/",views.EventPhotosView.as_view(),name="photos"),
path("<int:pk>/photos/add",views.AddPhotoView.as_view(),name="add-photo"),
path("<int:event_pk>/photos/<int:photo_pk>/delete/",views.delete_photo,name="delete-photo"),
path("<int:event_pk>/photos/<int:photo_pk>/edit/",views.EditPhotoView.as_view(),name="edit-photo"),
path("search/",views.search,name="search"),
path("approve/<int:pk>", views.approve, name = "approve"),
]

reservations/urls.py
from django.urls import path 
from . import views

app_name = "reservations"

urlpatterns = [
    path("<int:event_id>/register", views.register, name="register"),
    path("<int:event_id>/view_status", views.view_status, name="view_status"),
    path("cancel/<int:event_id>", views.cancel_registration, name="cancel")
]

templates/register/afterregister.html
{% extends "base.html" %}
{% load static %}
{% block page_name %}
{{Review}}
{% endblock page_name%}


{% block content %}
<style>
    .topic-events{
  margin-left: 3%;
  font-size: 5rem;
  z-index: 1000;
}

.dropdown .dropbtn {
  font-size: 16px;
  border: none;
  outline: none;
  padding: 10px 16px;
  background-color:inherit;
  font-family: inherit; /* Important for vertical align on mobile phones */
  margin: 0; /* Important for vertical align on mobile phones */
}

/* Dropdown content (hidden by default) */
.dropdown-content {
  display: none;
  position: absolute;
  background-color:#FEFFEC;
  min-width: 100px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
  opacity: 0.8;
}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {
  display: block;
}
.get:hover{
  font-weight: bold;
  font-weight: 17px;
}

/* intro-section */
.row1{
  padding-top: 100px;
}
/* .ss{
  display: block;
  position: relative;
  top:50%;
  left:50%;
  transform: translate(-50%,-50%);

} */
.img-div{
  /* margin:auto;
  position: relative; */
  height:600px;
  width:550px;
  display: flex;
  align-items: center;
  justify-content: center;
  /* overflow: hidden; */

}
.profile-intro-img{
  margin-top:50px;
  width: 100%;
}
.ss{
  display: flex;
  align-items: center;
  justify-content: center;
}
.profile-intro-heading{
color: rgba(65, 156, 214, 1);
font-size: 60px;
}
.event-info-div{
padding-top: 90px;

}

.event-info{
    width:80%;
    transform: translate(15%);
    text-align: center;
    overflow: hidden;
    /* width: 512px;
    height: 330px; */
    background: #FFFFFF;
    box-shadow: 0px 10px 25px rgba(0, 0, 0, 0.1);
    border-radius: 10px;
    position: relative;
    padding-top: 20px;
    padding-bottom: 20px;
    border: 1px solid black;
/* margin-left:90px; */
}

.table{
  transform: translate(15%);
  text-align: left;
/* width:80%; */
font-size: 30px;
margin-bottom: 30px;
}
@media only screen and (max-width: 992px) {
.profile-div{
  width:100%;
  transform: translate(0%);

}
.table{
  transform: translate(13%);

}
.profile-intro-heading{
  margin-top:70px;

}

}
.button-edit{
    background-color: #8646EF;
    margin-bottom: 2%;
    opacity: 0.9;
    color: white;
    width: 250px;
    height: 49px;
    border-radius: 25px;

}
.button-edit:hover {
    opacity: 1;
}
.button-text{
  font-size: 25px;
  padding-bottom: 0;


}

/* send message section */

.profile-intro-img-invisible{
  visibility: hidden;
  height:535px;
  width:489px;
}
@media only screen and (max-width: 992px) {
.profile-intro-img-invisible{
display:none;
}
}
.send-message-div{
  width:80%;
  transform: translate(15%);
    text-align: center;
    overflow: hidden;
    /* width: 512px;
    height: 330px; */
    background: #FFFFFF;
    border: 0.5px solid #C4C4C4;
box-sizing: border-box;

    position: relative;
padding-top: 40px;
padding-bottom: 20px;
}

.row2{
  margin-top:60px;

}
.A-circle {
    background: #C4C4C4;
    color: #fff;
    padding: 10px 20px;
    padding-top: 8px;
    border-radius: 50%;
    font-size: 35px;
font-weight: bold;
}
.A-circle-size{
  margin-bottom:20px;
  transform: scale(1.3);
}








.button-bottom-edit{
  transform: scale(1.2);
width:90%;
  margin-left:-30px;
}

.A-circle-size-bottom::after{
  position: relative;
  top: 10px;
  content:"{{event.organizer.first_name}}";
  font-size: 20px;
  font-weight: bold;
  display: block;
color: rgba(196, 196, 196, 1);


}
@media only screen and (max-width: 992px) {
  .button-bottom-edit{
  transform: scale(1);
  width: 220px;
  height: 49px;
  margin-left:0;
  margin-top: 30px;
}
}
.leave-review{
  font-size:calc(2vw + 12px);
  background-color:#8646EF;
  color:white;
  border-top-right-radius: 10px;
  border-top-left-radius: 1px;
}
.review-text{
  /* transform: translate(50%); */
margin:auto;
margin-top:5px;
  text-align: center;
  width: 70%;
  /* height: 250px; */
  background: #EAEAEA;
  border: 1px solid black;
border-radius: 10px;
}
textarea{
 width: 95%;
 height: 160px;
}

.button-submit{
  width: 150px;
  transform: scale(1);
  margin-top:20px;
margin-bottom: 20px;
}
.bottom-section{
  position: relative;
  /* bottom:100px; */
}
@media only screen and (max-width: 992px) {
  .bottom-section{
    position: static;
    margin-top:50px;
  }
  .review-text{
    /* transform: translate(50%); */
  width:90%;
  }
  .leave-review{
    padding-left: 10px;
    padding-right: 10px;
  }
}
</style>

<div class="intro container-fluid">
    <div class="row row1">
      <div class="col-lg-6">
        <div class="ss">


          <div class="img-div">
            <img class="profile-intro-img" src="{{event.first_photo}}" alt="">
          </div>
        </div>
      </div>

      <div class="col-lg-6">
        <h1 class="profile-intro-heading">{{ event.name }}</h1>
        <div class="container event-info-div">
          {% if ended %}
          <div class="event-info">
            <div class ="col-md-9">
              <table class="table">
                <tr>
                  <td>Event Ended</td>
                </tr>
                <tr>
                  <td>Scroll below to give a review</td>
                </tr>
              </table>
            </div>
          </div>
          {% else %}
          <div class="event-info">
            <table class="table">
              <tr>
                <td>Status:</td>
                <td style="color:#DFE248;">{{ reservation.status }}</td>
              </tr>
              <tr>
                <td>Date:</td>
                <td>{{event.event_date}}</td>
              </tr>
              <tr>
                <td>Venue:</td>
                <td>{{ event.city }}</td>
              </tr>
            </table>
            <form method="POST" action ="{% url 'reservations:cancel' event.id %}">
              {% csrf_token %}
              <button type="submit" class=" button-edit" data-aos="zoom-in">
                <p class="button-text">Cancel Registration</p>
              </button>
            </a>
          </div>
        </div>
      </div>
    </div>

  </div>


  <div class="intro container-fluid">
    <div class="row row1">
      <div class="col-lg-6">
        <img class="profile-intro-img-invisible" src="images/wwe.jpg" alt="">
      </div>
      <div class="col-lg-6">

        <div class="container" data-aos="slide-up">

          <div class="send-message-div">
            <h1>Contact your Event Host:</h1>
            <div class="container-fluid">
              <div class="row row2">
                <div class="col-lg-6">
                  <div class="A-circle-size A-circle-size-bottom">
                    <span class="A-circle">{{event.organizer.first_name|first}}</span>

                  </div>
                </div>
                <div class="col-lg-6">
                  <a href="{% url 'conversations:go' event.organizer.pk reservation.user.pk %}">
                    <button type="button" class=" button-edit button-bottom-edit" data-aos="zoom-in">
                      <p class="button-text">Send Message</p>
                    </button>
                  </a>
                </div>
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>

  </div>

{% if ended %}

  <div class="bottom-section" data-aos="fade-in">


    <div class="review-text ">


      
      <form action="{% url "events:event_detail" event.pk %}" method="post">
        {% csrf_token %}
        <p class="leave-review">This event has ended. Please leave a review:</p>
        <div class="rating">
        <p style="font-size:25px; font-weight:bold;">Rating out of 10: <input   style="width:50px;" type="text" name="rating" value=""></p>
        </div>
        <h3 style="margin-bottom:30px; padding-top:20px;text-align:left;margin-left:3%;">Leave a Review:</h3>
        <textarea placeholder="Your Comment" name="review"></textarea><br>

        <button type="submit" class=" button-edit button-submit" data-aos="zoom-in">
          <p class="button-text">Submit</p>
        </button>

      </form>
    </div>
  </div>
{% else %}
  <p>       </p>
  
{% endif %}
  <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init({
      duration: 900,
    });
  </script>

{% endblock %}