config/urls.py
from users import urls
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static #It helps us serve static file.

urlpatterns = [
    path("",include("core.urls",namespace="")),
    path("events/",include("events.urls",namespace="events")),
    path("users/",include("users.urls",namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from events import views as event_views
from . import views
app_name = "core"

urlpatterns =[
    path("",views.home_view,name="home"),
    path("events/",event_views.EventView.as_view(),name="event"),
    path("abutus/",views.aboutus, name="aboutus")
    ]

users/urls.py
from django.urls import path 
from . import views

app_name = "users"

urlpatterns = [
    path("login/",views.LoginView.as_view(),name="login"),
    path("login/github/",views.github_login,name="github-login"),
    path("login/github/callback/",views.github_callback,name="github-callback"),
    path("logout/",views.log_out,name="logout"),
    path("signup/",views.SignUpView.as_view(),name="signup"),
    path("verify/<str:key>/",views.complete_verification,name="complete-verification"),
    path("update-profile",views.UpdateProfileView.as_view(),name="update"),
    path("update-password",views.UpdatePasswordView.as_view(),name="password"),
    path("<int:pk>/",views.UserProfileView.as_view(),name="profile"),
]

users/models.py
import uuid
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.mail import send_mail
from django.urls.base import reverse
from django.utils.html import strip_tags
from django.template.loader import render_to_string
# Create your models here.
class User(AbstractUser):

    '''Custom User model'''

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE,"Female"),
        (GENDER_OTHER,"Other")
    )

    LOGIN_EMAIL = "email"
    LOGIN_GOOGLE = "google"
    LOGIN_GITHUB = "github"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL,"Email"),
        (LOGIN_GOOGLE,"Google"),
        (LOGIN_GITHUB,"Github"),
    )

    avatar = models.ImageField(upload_to = "avatars",blank = True)
    gender = models.CharField(choices=GENDER_CHOICES,max_length=10,blank=True)
    bio = models.TextField(blank=True)
    superorganizer = models.BooleanField(default = False)

    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=30,default="",blank=True)
    login_method = models.CharField(max_length=50,choices=LOGIN_CHOICES,default=LOGIN_EMAIL)
    
    def get_absolute_url(self):
        return reverse("users:profile",kwargs={'pk':self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:30]
            self.email_secret = secret
            # print("--------------------------------------")
            # print(self.email)
            # print("________________________________________")
            html_message = render_to_string("emails/verify_email.html",{"secret":secret})
            send_mail(
                f"Verify your Eventhub Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
                )
            self.save()

        return

users/forms.py
from django import forms
from django.forms import fields, widgets
from django.forms.fields import EmailField
from . import models


class LoginForm(forms.Form):

    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':"Email",'class':"myFieldclass"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Password",'class':"myFieldclass"}))

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password",forms.ValidationError("Password Wrong"))
        except models.User.DoesNotExist:
            self.add_error("email",forms.ValidationError("User does not exist"))

'''
class SignUpForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password_re = forms.CharField(widget=forms.PasswordInput,label="Confirm Password")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email="email")
            raise forms.ValidationError("User Already Exists with that Email.")
        except models.User.DoesNotExist:
            return email

    def clean_password_re(self):
        password = self.cleaned_data.get("password")
        password_re = self.cleaned_data.get("password_re")

        if password != password_re:
            raise forms.ValidationError("Password doesn't match")
        else:
            return password

    def save(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        #creating the user
        user = models.User.objects.create_user(email,email,password)
        user.first_name = first_name
        user.last_name =last_name
        user.save()
'''

class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ["first_name","last_name"]
        widgets={
            'first_name':forms.TextInput(attrs={'placeholder':"First Name",'class':"name first-name"}),
            'last_name':forms.TextInput(attrs={'placeholder':"Last name",'class':"name"}),
        }
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder':"Email",'class':"myFieldclass"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Password",'class':"myFieldclass"}))
    password_re = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Retype Password",'class':"myFieldclass"}),label="Confirm Password")

    # def clean_email(self):
    #     print("-----------------------wow----------------------------------------------")
    #     email = self.cleaned_data.get("email")
    #     try:
    #         models.User.objects.get(email="email")
    #         raise forms.ValidationError("User Already Exists with that Email.")
    #     except models.User.DoesNotExist:
    #         return email

    def clean_email(self):
        email = self.cleaned_data.get("email")
        print("----------------------------------------------------")
        print(models.User.objects.filter(email=email).exists())
        if models.User.objects.filter(email=email).exists():
            raise forms.ValidationError("User Already Exists with that Email.")
        else:
            return email

    def clean_password_re(self):
        password = self.cleaned_data.get("password")
        password_re = self.cleaned_data.get("password_re")

        if password != password_re:
            raise forms.ValidationError("Password doesn't match")
        else:
            return password

    def save(self,*args,**kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = super().save(commit=False)
        user.username = email
        user.email = email
        user.set_password(password)
        user.save()


class UpdateForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ["email","first_name","last_name","gender","bio","avatar"]
        widgets={
            'email':forms.TextInput(attrs={'placeholder':"Email",'class':"myFieldclass name first-name"}),
            'first_name':forms.TextInput(attrs={'placeholder':"First Name",'class':"myFieldclass name first-name"}),
            'last_name':forms.TextInput(attrs={'placeholder':"Last Name",'class':"myFieldclass name last-name"}),
            'bio':forms.Textarea( attrs={'maxlength':"20",'placeholder':"Write your bio here (Only 27 characters)",'class':"myFieldclass"}),
        }
    

users/views.py
import os
from django.forms import widgets
from django.views.generic.edit import UpdateView
import requests
from users import models
from django.contrib import auth
from django.http.response import HttpResponseRedirectBase
from django.views import View
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.views.generic import FormView,DetailView,UpdateView
from django.shortcuts import render,redirect,reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from . import forms,mixins
import users

# Create your views here.
'''
class LoginView(View):

    def get(self,request):
        form = forms.LoginForm()
        return render(request,"users/login.html",{"form":form})

    def post(self,request):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request,username=email,password=password)
            if user is not None:
                login(request,user)
                return redirect(reverse("core:event"))

        return render(request,"users/login.html",{"form":form})
'''

# implementing using form view

class LoginView(mixins.LoggedOutOnlyView,FormView):
    
    template_name = "users/login.html"
    form_class = forms.LoginForm
    # success_url = reverse_lazy("core:event")

    def form_valid(self,form):
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(self.request,username=email,password=password)
            if user is not None:
                login(self.request,user)
                messages.success(self.request,f"Welcome Back, {user.first_name}")
                return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:event")

def log_out(request):
    messages.info(request,f"See you later")
    logout(request)
    return redirect(reverse("core:home"))
 
 
class SignUpView(mixins.LoggedOutOnlyView,FormView):
    
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:event")

    def form_valid(self,form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request,username=email,password=password)
        if user is not None:
            login(self.request,user)
        
        # user.verify_email()
        # messages.success(self.request,"Verification link sent to your mail.")
        messages.success(self.request,"Verification is turned off.")
        return super().form_valid(form)
    
def complete_verification(request,key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # success message here
    except models.User.DoesNotExist:
        # failed message here
        pass
    messages.success(request,"Email Verified")
    return redirect(reverse("core:event"))
    


def github_login(self):
    client_id = os.environ.get("GITHUB_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    return redirect(f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user,user:email")

class GithubException(Exception):
    pass

def github_callback(request):
    try:
        client_id = os.environ.get("GITHUB_ID")
        client_secret = os.environ.get("GITHUB_SECRET")
        code = request.GET.get("code","None")
        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            result_json = token_request.json()
            error = result_json.get("error",None)
            if error is not None:
                return GithubException("Can't get the access token")
            else:
                access_token = result_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                email_request = requests.get(
                    "https://api.github.com/user/emails",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                email_json = email_request.json()
                profile_json = profile_request.json()
                # print(profile_json)
                username = profile_json.get("login",None)
                if username is not None:
                    name = profile_json.get("name")
                    email = email_json[0].get("email")
                    # user = models.User.objects.get(email=email)
                    try:
                        user = models.User.objects.get(email=email)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException (
                                f"Please login with:{user.login_method}"
                            )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(username=email,first_name=name,email=email,login_method = models.User.LOGIN_GITHUB,email_verified=True,)
                        user.set_unusable_password()
                        user.save()
                    login(request,user)
                    messages.success(request,f"Welcome Back, {user.first_name}")
                    return redirect(reverse("core:event"))

                    
                    # if user is not None:
                    #     return redirect(reverse("users:login"))
                    # else:
                    #     user = models.User.objects.create(username=email,first_name=name,email=email)
                    #     login(request,user)
                    #     return redirect(reverse("core:event"))
                else:
                    raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get code")
    except GithubException as err:
        messages.error(request,err)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):

    model = models.User    
    context_object_name = "user_obj"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)

class UpdateProfileView(mixins.EmailLoginOnlyView,mixins.LogInOnlyView,UpdateView):

    model = models.User
    form_class = forms.UpdateForm
    template_name = "users/update-profile.html"
    context_object_name = "user_edit"
    # fields = {
    #     "first_name",
    #     "last_name",
    #     "avatar",
    #     "gender",
    #     "bio",    
    # }
    
    def get_object(self,queryset=None):
        return self.request.user


    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        if email != "":
            print("yo runvayo")
            self.object.username = email
        self.object.save()
        messages.success(self.request,"Profile updated")
        return super().form_valid(form)


class UpdatePasswordView(mixins.LogInOnlyView,SuccessMessageMixin,PasswordChangeView):
    
    template_name= "users/update-password.html"
    success_message = "Password Updated"
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["old_password"].widget.attrs = {"class":"myFieldclass"}
        form.fields["new_password1"].widget.attrs = {"class":"myFieldclass","onfocus":"closeye()"}
        form.fields["new_password2"].widget.attrs = {"class":"myFieldclass","onfocus":"closeye()"}
        return form

    def get_success_url(self):
        return self.request.user.get_absolute_url()

templates/users/update-profile.html
{% extends "base.html" %}

{% load static %}

{% block page_name %}
    Update Profile
{% endblock page_name %}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}

{% comment %}
    <style>
        .other{
            padding-top: 80px;
            display: block;
        }
    </style>
    <div class="container-fluid other">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button>Update Profile</button>
        </form>
        
    </div>
{% endcomment %}

<style>
    @import url("https://fonts.googleapis.com/css2?family=Muli&display=swap");

* {
  margin: 0;
  padding: 0;
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
}

body {
  font-family: "Muli", sans-serif;
}

.container-main{
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  overflow-y: hidden ;
}
.box{
  background: rgba(65, 156, 214, 0.7);
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  position: relative;
  overflow: hidden;
}
.box-1{
  height: 55rem;
  width: 40rem;
}
.circle{
  height: 20rem;
  width: 20rem;
  background-color:rgba(172, 218, 248, 0.5);
  position: absolute;
  border-radius: 50%;
  left: -6rem;
  bottom: -7rem;
}
.circle-2{
  height:3.5rem;
  width: 3.5rem;
  background-color:rgba(172, 218, 248, 0.5);
  position: absolute;
  border-radius: 50%;
  top:16rem;
  left:3.5rem;  
}
.triangle{
  height: 7rem;
  width: 7rem;
  position: absolute;
  background-color:rgba(172, 218, 248, 0.5);
  clip-path: polygon(50% 0%, 0% 100%, 100% 100%);
  transform: rotate(-29.99deg);
  right: 5rem;
  bottom: 12rem;
}
.star{
  height: 8rem;
  width: 8rem;
  position: absolute;
  background-color:rgba(172, 218, 248, 0.5);
  clip-path: polygon(50% 0%, 61% 35%, 98% 35%, 68% 57%, 79% 91%, 50% 70%, 21% 91%, 32% 57%, 2% 35%, 39% 35%);
  transform: rotate(-25.36deg);
  top:-2rem;
  right: -1rem;
}
.main-text{
  /* font-family: Muli; */
  color: #E3EBF0;
  font-size: 3rem;
  text-align: center;
}
.secondary-text{
  font-size: 2rem;
  margin-top: 8rem;
  color: #E3EBF0;
  font-style: normal;
  font-weight: normal;
}
.password-change-main
{
  /* margin-top: 3rem; */
  padding: 0.1rem;
  height:2.5rem;
  width:16rem;
  background: #419CD6;
  border-radius: 15px;
  border: none;
  z-index: 100;
  vertical-align: middle;
}
.text-inside-buttom{
  font-size: 1.6rem;
  color: #E3EBF0;
}

.box-2{
  height: 55rem;
  width: 55rem;
  background: #E5E5E5;
}

.right-side{
  color: gray;
  margin-bottom: 2rem;
  display: none;
}


.cross{
  position: absolute;
  right: 4rem;
  top: 7rem;
}
.navbar{
    display: none;
}
footer{
    display: none;
}
/* profile photo*/
.A-circle {
        background: #C4C4C4;
        color: #fff;
        padding: 10px 20px;
        padding-top: 8px;
        border-radius: 50%;
        font-size: 35px;
        font-weight: bold;
    }
    .profile-image{
        border-radius: 50%;
        height: 5rem;
        width: 5rem;
    }

    .A-image{
        border-radius: 50%;
        margin-bottom: 10px;
    }

    .A-circle-size {
        margin-bottom: 20px;
        transform: scale(1.3);
    }
textarea{
    resize: none;
    height:55px;
}
.spacer{
  margin-bottom: 1.6rem;
}
.input-group-text{
    padding-right: 20px;
}

.myFieldclass{
    border: none;
    border-radius: 1px;
    padding: 10px;
    width: 20rem;
}

.myFieldclass:focus-within
{
    /* box-sizing: border-box; */
    outline: none;
    outline: thin solid green;
    
}

.name-space{
  padding-right: 41px;
}
.gender-space{
  padding-right: 35px;
}
.bio-space{
  padding-right: 59px;
}
.tertiary-text{
  font-size: medium;
  background-color: gold;
  border-radius: 20px;
}
/* #id_avatar {
	position: relative;
	overflow: hidden;
	margin: 10px;
}
#id_avatar input.upload {
	position: absolute;
	top: 0;
	right: 0;
	margin: 0;
	padding: 0;
	font-size: 20px;
	cursor: pointer;
	opacity: 0;
	filter: alpha(opacity=0);
} */
#avatar-clear_id{
  display: inline-block;
  flex-wrap: wrap;
  width: 20px;
  justify-content: center;
}
.for-input{
  display: flex;
  width: auto;
  flex-direction: column;
  text-align: center;
}
.for-input input{
  margin-left: 90px;
}
input[type="checkbox"]{
  margin-left: 200px;
  height: 15px;
}
.image-input{
  flex-direction: column;
  align-items: center;
}

/* .input-group label{
  display: none;
} */

@media only screen and (max-width: 650px) {
  .box-1{
    display: none;
  }
  .right-side{
    display: block;
  }
}

</style>
<div class="container-main">
    <div class="box box-1">
        <div class="circle"></div>
        <div class="circle-2"></div>
        <div class="star"></div>
        <div class="triangle"></div>
        <div class="content">
            <p class="main-text">Edit your profile detail:</p>
        <div>
            {% if user_edit.avatar %}
            <div class="A-image">
                <img class="profile-image" src="{{user_edit.avatar.url}}" alt="profile-img">
            </div>
            {% else %}
            <div class="A-circle-size">
                <span class="A-circle">{{user_edit.first_name|first}}</span>
            </div>
            {% endif %}
            <h3 class="profile-name">
                {{user_edit.first_name}}
                 {% if user_edit.superorganizer %}
                  <img style="margin-bottom: 2px;" class="verified-blue" src="{% static 'images/user-detail/verified-sign.svg'%}">
                  {% endif %}
                </h3>
        </div>


        {% if object.login_method == "email" %}
            <p class="secondary-text">Wanna change your password?</p>
            <a href="{% url 'users:password' %}">
              <button class="password-change-main">
                  <p class="text-inside-buttom">Change Password</p>
              </button>
            </a>
            {% else %}
            <p class="secondary-text">You are logged in with {{object.login_method}}.</p>
            <p class="tertiary-text">So, We cannot change your email and password.</p>
            {% endif %}
        </div>
    </div>
    <div class="box box-2">
        <div class="content">
          <a href="{% url 'users:profile' object.pk %}">
            <div class="cross"><img src="{% static 'images/user-detail/cross.svg'%}" alt=""></div>
          </a>
            <p class="main-text right-side"><b>Edit your profile</b></p>
            {%comment%}
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button>Update Profile</button>
                </form>
            {%endcomment%}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
            <div>
              {% if object.login_method == "email" %}
                <div class="input-group flex-nowrap spacer w-100 ">
                  <span class="input-group-text name-space" id="addon-wrapping">Email</span>
                  {{form.email}}
                </div>
                {% else %}
                <div class="input-group flex-nowrap spacer w-100 " style="visibility: hidden;">
                  <span class="input-group-text name-space" id="addon-wrapping">Email</span>
                  {{form.email}}
                </div>
                {% endif %}
                <div class="input-group flex-nowrap spacer w-100 ">
                    <span class="input-group-text name-space" id="addon-wrapping">Name</span>
                    {{form.first_name}}
                </div>

                <div class="input-group flex-nowrap spacer w-100 ">
                    <span class="input-group-text" id="addon-wrapping">Surname</span>
                    {{form.last_name}}
                </div>

                <div class="input-group flex-nowrap spacer w-100 ">
                    <span class="input-group-text gender-space" id="addon-wrapping">Gender</span>
                    {{form.gender}}
                </div>
                    <br />
                <div class="input-group flex-nowrap spacer w-100 ">
                        <span class="input-group-text bio-space" id="addon-wrapping">Bio</span>
                        {{form.bio}}
                </div>
                <br />
                <div class="input-group flex-nowrap spacer w-100 image-input ">
                    <span class="input-group-text" style="padding-left: 50px; padding-right: 50px; margin-bottom: 10px;" id="addon-wrapping">Avatar</span>
                    <div class="for-input">
                      {{form.avatar}}
                    </div>
                </div>

                <div class="login">
                        <button class="btn login-button" style="background-color: #419CD6; width:10rem; border-radius: 10px;" type="submit">
                            <span style="font-size: 15px; vertical-align: center; color: white;"> 
                                Update Profile
                            </span>
                        </button>
                </div>
              </div>
            </form>
        </div>
    </div>
</div>

<script>
  
$(".foot-icon").hover(function() {

$(this).css("opacity","1");
$(this).css("transform","scale(1.2)");

}, function(){
$(".foot-icon").css("opacity","");
$(this).css("transform","");
}
);
</script>
    {% endblock %}

templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}
{% block page_name %}
{{user_obj.first_name}}'s Profile
{% endblock page_name %}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}
<style>
    /* profile-chat*/
    .profile-chat {
        padding-top: 90px;

    }

    .profile-div {
        margin-left: 25%;
        margin-right: 25%;
        text-align: center;
        overflow: hidden;
        width: 50%;
        border:1px solid black;
        box-shadow: 0px 10px 25px rgba(0, 0, 0, 0.3);
        position: relative;
        padding-top: 40px;
        padding-bottom: 20px;
        border-radius: 8px;
    }

    /*/*.profile-logo{
    background-color:#C4C4C4 ;
    width: 50%;
    margin-left: 40%;
    margin-top: 5%;
    height: 50%;
    border-radius: 50%;
    padding-left: 25%;
    padding-right: 25%;
}*/
    .A-circle {
        background: #C4C4C4;
        color: #fff;
        padding: 10px 20px;
        padding-top: 8px;
        border-radius: 50%;
        font-size: 35px;
        font-weight: bold;
    }
    .profile-image{
        border-radius: 50%;
        height: 5rem;
        width:5rem;
    }

    .A-image{
        border-radius: 50%;
        margin-bottom: 10px;
    }

    .A-circle-size {
        margin-bottom: 20px;
        transform: scale(1.3);
    }

    .profile-name {
        padding-top: 2%;
    }

    .profile-img {
        padding-top: 2%;
    }

    .letter {
        position: absolute;
        left: 46%;
        top: 17%;
    }

    .verified-blue {
        padding-bottom: 2%;
    }

    .button-edit {
        background-color: #8646EF;
        margin-bottom: 2%;
        opacity: 0.9;
        color: white;
        width: 40%;
        height: 49px;
        border-radius: 25px;

    }

    .button-edit:hover {
        opacity: 1;
    }

    .edit {
        font-size: 25px;
        padding-bottom: 80%;

    }

    .event-owner {
        text-align: center;
        margin-top: 3%;
    }
    .topic-events{
        display: none;
    }
    .user-event-list{
        margin-top: -90px;
        margin-bottom: 40px;
    }
</style>

<div class="container profile-chat">

    <div class="profile-div">
        <!--<div class="profile-logo">
            <h1>A</h1>
        </div> -->
        {% if user_obj.avatar %}
        <div class="A-image">
            <img class="profile-image" src="{{user_obj.avatar.url}}" alt="profile-img">
        </div>
        {% else %}
        <div class="A-circle-size">
            <span class="A-circle">{{user_obj.first_name|first}}</span>
        </div>
        {% endif %}



        <h3 class="profile-name">{{user_obj.first_name}} {{user_obj.last_name}} {% if user_obj.superorganizer %} <img class="verified-blue" src="{% static 'images/user-detail/verified-sign.svg' %}">{% endif %}</h3>
        {% if user == user_obj %}
        <a href="{% url 'users:update' %}">
            <button type="button" class=" button-edit">
                <p class="edit">Edit profile</p>
            </button>
        </a>
        {% endif %}


    </div>
</div>

<div class="event-owner">
    <h1>{{user_obj.first_name}}'s Event</h1>
</div>

<div class="user-event-list">
    {% for event in user_obj.events.all %}
            {% include 'partials/event_card.html' with event=event %}
        {% endfor %}
</div>


{% endblock content %}