config/urls.py
from users import urls
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static #It helps us serve static file.

urlpatterns = [
    path("",include("core.urls",namespace="")),
    path("events/",include("events.urls",namespace="events")),
    path("users/",include("users.urls",namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views
app_name = "conversations"

urlpatterns = [
    path("go/<int:organizer_pk>/<int:participants_pk>/",views.go_conversation,name="go"),
    path("<int:pk>/",views.ConversationDetailView.as_view(),name="detail")
]

core/urls.py
from django.urls import path
from events import views as event_views
from . import views
app_name = "core"

urlpatterns =[
    path("",views.home_view,name="home"),
    path("events/",event_views.EventView.as_view(),name="event"),
    path("abutus/",views.aboutus, name="aboutus")
    ]

events/urls.py
from events.forms import CreateEventForm
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
path("create/",views.CreateEventView.as_view(),name="create"),
path("<int:pk>",views.event_detail,name="event_detail"),
path("<int:pk>/edit",views.EditEventView.as_view(),name="edit"),
path("<int:pk>/photos/",views.EventPhotosView.as_view(),name="photos"),
path("<int:pk>/photos/add",views.AddPhotoView.as_view(),name="add-photo"),
path("<int:event_pk>/photos/<int:photo_pk>/delete/",views.delete_photo,name="delete-photo"),
path("<int:event_pk>/photos/<int:photo_pk>/edit/",views.EditPhotoView.as_view(),name="edit-photo"),
path("search/",views.search,name="search"),
path("approve/<int:pk>", views.approve, name = "approve"),
]

events/forms.py
from django.forms.models import ModelForm
import users
from django import forms
from django.forms import fields
from django.shortcuts import redirect,reverse
from . import models


class SearchForm(forms.Form):

    #address = forms.CharField(initial="Anywhere")
    address = forms.CharField(initial="Anywhere", required=False)
    address.widget.attrs.update({'class':'form-control'})
    city = forms.CharField(initial="Anywhere", required=False)
    city.widget.attrs.update({'class':'form-control'})
    event_type = forms.ModelChoiceField(required=False,empty_label="Any Kind", queryset=models.EventType.objects.all())
    event_type.widget.attrs.update({'class':'form-control'})
    price = forms.IntegerField(required=False)
    price.widget.attrs.update({'class':'form-control'})
    
    


    

class UpdateForm(forms.ModelForm):
    class Meta:
        model = models.Event
        fields = [
            "name",
            "description",
            "city",
            "address", 
            "price",
            "event_date",
            "event_start",
            "event_end",
            "event_type",
            "event_rule", 
        ]
        widgets={
            'name':forms.TextInput(attrs={'placeholder':"Name of the event",'class':"myFieldclass event-name"}),
            'description':forms.Textarea(attrs={'placeholder':"Enter description for your event",'class':'myFieldClass event-description'}),
            'city':forms.TextInput(attrs={'placeholder':"Event city name",'class':"myFieldclass event-city"}),
            'address':forms.TextInput(attrs={'placeholder':"Enter address",'class':"myFieldclass event-address"}),
            'price':forms.NumberInput(attrs={'placeholder':"Price",'class':"myFieldclass event-price"}),
            'event_date':forms.DateInput(attrs={'placeholder':"Year:Month:Day",'class':"myFieldclass event-date date"}),
            'event_start':forms.TimeInput(attrs={'placeholder':"H:M:S",'class':"myFieldclass event-end-time time"}),
            'event_end':forms.TimeInput(attrs={'placeholder':"H:M:S",'class':"myFieldclass event-start-time time"}),

            # 'first_name':forms.TextInput(attrs={'placeholder':"First Name",'class':"myFieldclass name first-name"}),
            # 'last_name':forms.TextInput(attrs={'placeholder':"Last Name",'class':"myFieldclass name last-name"}),
            # 'bio':forms.Textarea( attrs={'maxlength':"20",'placeholder':"Write your bio here (Only 27 characters)",'class':"myFieldclass"}),
        }

class CreatePhotoForm(forms.ModelForm):

    class Meta:
        model = models.Photo
        fields = {'caption','file'}

    def save(self,pk,*args,**kwargs):
        photo = super().save(commit=False)
        event = models.Event.objects.get(pk=pk)
        photo.event = event
        photo.save()

class CreateEventForm(forms.ModelForm):
    class Meta:
        model = models.Event
        fields = [
        "name",
        "description",
        "city",
        "address", 
        "price",
        "event_date",
        "event_start",
        "event_end",
        "event_type",
        "event_rule", 
        ] 
        widgets={
            'name':forms.TextInput(attrs={'placeholder':"Name of the event",'class':"myFieldclass event-name"}),
            'description':forms.Textarea(attrs={'placeholder':"Enter description for your event",'class':'myFieldClass event-description'}),
            'city':forms.TextInput(attrs={'placeholder':"Event city name",'class':"myFieldclass event-city"}),
            'address':forms.TextInput(attrs={'placeholder':"Enter address",'class':"myFieldclass event-address"}),
            'price':forms.NumberInput(attrs={'placeholder':"Price",'class':"myFieldclass event-price"}),
            'event_date':forms.DateInput(attrs={'placeholder':"Year:Month:Day",'class':"myFieldclass event-date date"}),
            'event_start':forms.TimeInput(attrs={'placeholder':"HH:MM:SS",'class':"myFieldclass event-end-time time"}),
            'event_end':forms.TimeInput(attrs={'placeholder':"HH:MM:SS",'class':"myFieldclass event-start-time time"}),

            # 'first_name':forms.TextInput(attrs={'placeholder':"First Name",'class':"myFieldclass name first-name"}),
            # 'last_name':forms.TextInput(attrs={'placeholder':"Last Name",'class':"myFieldclass name last-name"}),
            # 'bio':forms.Textarea( attrs={'maxlength':"20",'placeholder':"Write your bio here (Only 27 characters)",'class':"myFieldclass"}),
        }
        

    def save(self,*args,**kwargs):
        event = super().save(commit = False)
        return event

events/views.py
'''
from django.shortcuts import render,redirect
from django.core.paginator import Paginator,EmptyPage
from . import models

# Create your views here.
def all_events(request):
    page = request.GET.get("page",1)
    event_list = models.Event.objects.all()
    paginator = Paginator(event_list,6)
    try:
        events = paginator.page(int(page))
        return render(request,"events/all_events.html",{"page":events})
    except EmptyPage:
        return redirect('/events')

'''
import datetime
import reviews
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import render,redirect,reverse
from django.http import Http404
from django.views.generic import ListView,UpdateView, CreateView, FormView
from django.core.paginator import Paginator
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from users.models import User
from reservations.models import Reservation
from reviews.models import Review
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views.generic.edit import CreateView, FormView
from users import mixins as user_mixins
from . import models,forms
from django.db.models import Q


class EventView(ListView):
    
    '''Eventview defination'''
    model = models.Event
    paginate_by = 8
    paginate_orphans = 4
    context_object_name = "events"
    

def event_detail(request,pk):
    if request.method == "POST":
        event = models.Event.objects.get(pk = pk)
        user = request.user
        review = request.POST["review"]
        rating = request.POST["rating"]
        Review.objects.create(review= review, rating = rating, user = user, event = event)

    current = datetime.datetime.now()
    now = datetime.date(current.year, current.month, current.day)
    try:
        a = False
        event = models.Event.objects.get(pk=pk)
        ended = event.event_date > now
        if request.user.is_authenticated: 
            reservation = Reservation.objects.filter(user=request.user)
            for r in reservation:
                if r.event == event:
                    a = True
                    break
                else:
                    continue
        args = {
            "event":event,
            "participated": a,
            "ended": ended
        }
        return render(request,"events/event_detail.html", args)
    except models.Event.DoesNotExist:
        raise Http404()

def approve(request, pk):
    event = models.Event.objects.get(pk = pk)
    participants = Reservation.objects.filter(event = event)
    if request.method == "POST":
        if request.POST["button_checker"] != "canceled":
            user_id = request.POST["user_id"]
            user = User.objects.get(pk = user_id)
            update_status = Reservation.objects.get(event = event, user = user)
            update_status.status = "confirmed"
            update_status.save()
        else:
            u_id = request.POST["u_id"]
            user = User.objects.get(pk = u_id)
            update_status = Reservation.objects.get(event = event, user = user)
            update_status.status = "canceled"
            update_status.save()
            
    args = {
        "event": event,
        "participants": participants,
    }
    return render(request, "events/approve.html", args)
    
def search(request):
    
    city = request.GET.get("city")
    if city:
        form = forms.SearchForm(request.GET)
        if form.is_valid():
            address = form.cleaned_data.get("address")
            city = form.cleaned_data.get("city")
            event_type =form.cleaned_data.get("event_type")
            price = form.cleaned_data.get("price")
            super_organizer = form.cleaned_data.get("super_organizer")

            filter_args = {}

            if address != "Anywhere":
                filter_args["address__startswith"] = address

            if city != "Anywhere":
                filter_args["city__startswith"] = city

            if event_type is not None:
                filter_args["event_type"] = event_type

            if price is not None:
                filter_args["price__lte"] = price

            if super_organizer is True:
                filter_args["organizer__superorganizer"] = True

            
            qs = models.Event.objects.filter(**filter_args)
            paginator = Paginator(qs,6,orphans=3)
            page = request.GET.get("page",1)
            events = paginator.get_page(page)
            return render(request, "events/search.html",{"form":form,"events":events})

    else:

        form = forms.SearchForm()

    return render(request, "events/search.html",{"form":form,})


'''Implementing searching without using django form'''
'''
def search(request):
    city = request.GET.get("city","Anywhere")
    city = str.capitalize(city)
    address = request.GET.get("address","Anywhere")
    event_type = int(request.GET.get("event_type",0))
    event_types = models.EventType.objects.all()
    price = int(request.GET.get("price",0))
    super_organizer = bool(request.GET.get("super_organizer",False))
    choices = {
        "event_types":event_types,
    }

    form = {
        "s_event_type":event_type,
        "s_city":city,
        "price":price,
        "address":address,
        "super_organizer":super_organizer,
    }
    filter_args = {}

    if city != "Anywhere":
        filter_args["city__startswith"] = city

    if event_type != 0:
        filter_args["event_type__pk__exact"] = event_type

    if price != 0:
        filter_args["price__lte"] = price

    if super_organizer is True:
        filter_args["organizer__superorganizer"] = True

    events = models.Event.objects.filter(**filter_args)
    return render(request, "events/search.html",{**form,**choices,"events":events,"price":price,"super_organizer":super_organizer,})
'''


class EditEventView(user_mixins.LogInOnlyView,UpdateView):

    model = models.Event
    template_name = "events/event_edit.html"
    form_class =forms.UpdateForm
    # fields = [
    # "name",
    # "description",
    # "city",
    # "address", 
    # "price",
    # "event_date",
    # "event_start",
    # "event_end",
    # "event_type",
    # "event_rule", 
    # ]

    def get_object(self,queryset=None):
        event = super().get_object(queryset=queryset)
        if(event.organizer.pk != self.request.user.pk):
            raise Http404()
        return event

class EventPhotosView(user_mixins.LogInOnlyView,DetailView):
    model = models.Event
    template_name = "events/event_photos.html"
    
    def get_object(self,queryset=None):
        event = super().get_object(queryset=queryset)
        if(event.organizer.pk != self.request.user.pk):
            raise Http404()
        return event


@login_required
def delete_photo(request,event_pk,photo_pk):
    user = request.user
    try:
        event = models.Event.objects.get(pk=event_pk)
        if event.organizer.pk != user.pk:
            messages.error(request,"Can't delete that photo")
        else:
            models.Photo.objects.filter(pk = photo_pk).delete()
        return redirect(reverse("events:photos",kwargs={"pk":event_pk}))
    except models.Event.DoesNotExist:
        return redirect(reverse("core:home"))

class EditPhotoView(user_mixins.LogInOnlyView, SuccessMessageMixin,UpdateView):
    
    model = models.Photo
    template_name = "events/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = (
        "caption",
    )
    
    def get_success_url(self):
        event_pk = self.kwargs.get("event_pk")
        return reverse("events:photos",kwargs={"pk":event_pk})


class AddPhotoView(user_mixins.LogInOnlyView,FormView):
    model = models.Photo
    template_name = "events/photo_create.html"
    fields = ["caption","file"]
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request,"Photo Uploaded")
        return redirect(reverse("events:photos",kwargs={"pk":pk}))


class CreateEventView(user_mixins.LogInOnlyView,FormView):
    form_class = forms.CreateEventForm
    template_name = "events/event_create.html"

    def form_valid(self,form):
        event = form.save()
        event.organizer = self.request.user
        event.save()
        form.save_m2m()
        messages.success(self.request,"Event Created")
        return redirect(reverse("events:event_detail",kwargs ={"pk":event.pk}))
        

templates/events/approve.html
{% extends "base.html" %}
{% load static %}
{% block page_name %}
Approve
{% endblock page_name%}

{% block content %}

    <h1>Users who have registered in your Event.</h1>
    <div class="container" style="margin-top:50px">
      <table class="table table-striped">
        <tr>
          <th>Username</th>
          <th>Status</th>
          <th>Approval</th>
          <th>Chat</th>
          <th>Cancel</th>
        </tr>
        {% for p in participants %}
        <tr>
          <td>{{ p.user.first_name }} {{p.user.last_name}}</td>
          <td>
            <h6>{{p.status}}</h6>
          </td>
          <td>
            <!--if approved dont show button else button-->
            {% if p.status == "confirmed" %}
            <h6 class="text-success">Confirmed</h6>
            {% else %}
            <form method="post" action="{% url 'events:approve' p.event.pk %}">
              {% csrf_token %}
              <input type="hidden" name="button_checker" value="not_canceled" />
              <input
                type="hidden"
                name="user_id"
                value="{{p.user.id}}"
              />
              <button type="submit" class="btn btn-success">Confirm</button>
            </form>
            {% endif %}
          </td>
          <td>
            <a
              href="{% url 'conversations:go' p.event.organizer.pk p.user.pk %}"
              ><button type="submit" class="btn btn-success">Chat</button></a
            >
          </td>
          <td>
            {% if p.status == "canceled" %}
            <h6 class="text-danger">Canceled</h6>
            {% else %}
            <form method="post" action="{% url 'events:approve' p.event.pk %}">
              {% csrf_token %}
              <input type="hidden" name="button_checker" value="canceled" />
              <input
                type="hidden"
                name="u_id"
                value="{{p.user.id}}"
              />
              <button type="submit" class="btn btn-danger">Cancel</button>
            </form>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
{% endblock %}

templates/events/event_list.html
{% extends "base.html" %}

{% block page_name %}
    Events
{% endblock page_name%}


{% block content %}
    {% for event in events %}
        {% include 'partials/event_card.html' with event=event %}
    {% endfor %}

    

    <div class="contaier-fluid next-event" style="margin-top:50px; margin-bottom: 50px;">
         <h5>
            {% if page_obj.has_previous %}
                <a style="text-decoration: none;" href="?page={{page_obj.previous_page_number}}"> &#8592 Previous</a>
            {% endif %}
                Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            {% if page_obj.has_next %}
                <a style="text-decoration: none;" href="?page={{page_obj.next_page_number}}">Next &#8594</a>
            {% endif %}
            </h5>
    </div>
    
{% endblock content %}

templates/events/event_photos.html
{% extends "base.html" %}

{% load static %}

{% block page_name %}
    {{event.name}}'s Photos 
{% endblock page_name %}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}



<style>
    @import url("https://fonts.googleapis.com/css2?family=Muli&display=swap");
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap');

* {
  margin: 0;
  padding: 0;
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
}

body {
  font-family: "Muli", sans-serif;
}

footer{
  display: none;
}
.container-main{
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  /* height: 100vh; */
  padding-top: 100px;
  padding-bottom: 50px;
  overflow-y: scroll ;
}

.mini-container{
  display:flex;
  width:75%;
  justify-content:space-between;
  padding:20px;
  box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
  border-radius:10px;
  margin-bottom: 20px;
}

.caption{
  margin-left:15px;
  float:right;
  font-family: 'Montserrat', sans-serif;
  font-weight:500;
}
.image-event{
  height:80px;
  width:100px;
}
.two-button{
  display:flex;
  flex-direction:column;
  align-self: center;
}
.btn-photo{
  width:9rem;
  border:none;
  color:white;
  padding:10px;
  border-radius:12px;
}
.btn-photo-edit{
  background-color:tomato;
}
.btn-photo-delete{
  margin-top:8px;
  background-color:black;
}


@media only screen and (max-width: 650px) {
  .cross{
    position: absolute;
    right: 4rem;
    top: 6rem;
  }
}

</style>
<div class="container-main">
  {%for photo in event.photos.all %}
  <div class="mini-container">
    <div class="together">
      <img class="image-event" src="{{photo.file.url}}" alt="" >
      <span class="caption">{{photo.caption}}</span>
    </div>
    <div class="two-button">
      <a href="{% url 'events:edit-photo' event.pk photo.pk %}"><button class="btn-photo btn-photo-edit">Edit</button></a>
      <a href="{% url 'events:delete-photo' event.pk photo.pk %}"><button class="btn-photo btn-photo-delete">Delete</button></a>
    </div>
  </div>
  {% endfor %}
  <div style="display: flex;">
        <a href="{% url 'events:add-photo' event.pk %}"><button class="btn-photo" style="background-color:dodgerblue;">Upload photo</button></a>
        
        <a href="{% url 'events:edit' event.pk %}"><button class="btn-photo" style="background-size: white;
        color: black; border: 1px solid dodgerblue; margin-left: 30px;
        width: 180px;">Back to event edit</button></a>
  </div>
</div>

<script>
 
</script>
    {% endblock %}

templates/events/photo_create.html
{% extends "base.html" %}

{% load static %}

{% block page_name %}
    Upload Photo 
{% endblock page_name %}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}



<style>
    @import url("https://fonts.googleapis.com/css2?family=Muli&display=swap");

* {
  margin: 0;
  padding: 0;
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
}

body {
  font-family: "Muli", sans-serif;
}

.container-main{
  display: flex;
  justify-content: center;
  align-items: center;
  /* height: 100vh; */
  padding-top: 100px;
  padding-bottom: 255px; 
  overflow-y: scroll ;
}
.box{
  background: rgba(65, 156, 214, 0.7);
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  position: relative;
  overflow: hidden;
}

.main-text{
  /* font-family: Muli; */
  color: dodgerblue;
  font-size: 3rem;
  font-weight: 800;
  text-align: center;
}
.secondary-text{
  font-size: 2rem;
  margin-top: 8rem;
  color: #E3EBF0;
  font-style: normal;
  font-weight: normal;
}
.password-change-main
{
  /* margin-top: 3rem; */
  padding: 0.1rem;
  height:2.5rem;
  width:16rem;
  background: #419CD6;
  border-radius: 15px;
  border: none;
  z-index: 100;
  vertical-align: middle;
}
.text-inside-buttom{
  font-size: 1.6rem;
  color: #E3EBF0;
}

.box-2{
  height: 55rem;
  width: 55rem;
  background: #E5E5E5;
}

.right-side{
  color: gray;
  margin-bottom: 2rem;
  display: none;
}


.cross{
  position: absolute;
  right: 4rem;
  top: 6rem;
}

/* profile photo*/
.A-circle {
        background: #C4C4C4;
        color: #fff;
        padding: 10px 20px;
        padding-top: 8px;
        border-radius: 50%;
        font-size: 35px;
        font-weight: bold;
    }
    .profile-image{
        border-radius: 50%;
        height: 5rem;
        width: 5rem;
    }

    .A-image{
        border-radius: 50%;
        margin-bottom: 10px;
    }

    .A-circle-size {
        margin-bottom: 20px;
        transform: scale(1.3);
    }
textarea{
    resize: none;
    height:55px;
}
.spacer{
  margin-bottom: 1.6rem;
}
.input-group-text{
    padding-right: 20px;
}

.myFieldclass{
    border: 1px solid dodgerblue;
    border-radius: 1px;
    padding: 10px;
    width: 20rem;
}

.myFieldclass:focus-within
{
    /* box-sizing: border-box; */
    outline: none;
    outline: thin solid green;
    
}
.event-description{
  height: 450px;
  border: 1px solid dodgerblue;
    border-radius: 1px;
    padding: 10px;
}
.event-description:focus-within
{
    /* box-sizing: border-box; */
    outline: none;
    outline: thin solid green;
    
}

.name-space{
  padding-right: 55px;
}
.price-space{
  padding-right: 65px;
}
.start-time-space{
  padding-right: 27px;
}
.end-time-space{
  padding-right: 35px;
}
.city-space{
  padding-right: 75px;
}
.address-space{
  padding-right: 41px;
}
.event-type-space{
  padding-right: 22px;
}
.event-description-space{
  height: 450px;
}
.time{
  width: 100px;
}
.tertiary-text{
  font-size: medium;
  background-color: gold;
  border-radius: 20px;
}


@media only screen and (max-width: 650px) {
  .cross{
    position: absolute;
    right: 4rem;
    top: 6rem;
  }
}

</style>
<div class="container-main">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
            <p class="main-text">Upload Photo For The Event:</p>

              <div class="input-group flex-nowrap spacer w-100 " >
                <span class="input-group-text name-space" id="addon-wrapping">Caption</span>
                {{form.caption}}
              </div>
              {% if form.caption.errors %}
                    {% for error in form.caption.errors %}
                        <span style="color: red; position: relative; top: -10px; left: -20px;">{{error}}</span>
                    {% endfor %}
              {% endif %}
              <div class="input-group flex-nowrap spacer w-100 " >
                <span class="input-group-text address-space" id="addon-wrapping">Photo</span>
                {{form.file}}
              </div>
              {% if form.file.errors %}
                  {% for error in form.file.errors %}
                      <span style="display:inline-block; color:  red; position: relative; top: -10px; left: 20px;">{{error}}</span>
                  {% endfor %}
            {% endif %}        
          <!-- <a href="">
            <div class="cross"><img src="{% static 'images/user-detail/cross.svg'%}" alt=""></div>
          </a> -->
                <div class="login">
                        <button class="btn login-button" style="background-color: #419CD6; width:10rem; border-radius: 10px;" type="submit">
                            <span style="font-size: 15px; vertical-align: center; color: white;"> 
                                Add Photo
                            </span>
                        </button>
                </div>
    </form>
</div>

<script>
 
</script>
    {% endblock %}

templates/events/photo_edit.html
{% extends "base.html" %}

{% load static %}

{% block page_name %}
    Update Photo 
{% endblock page_name %}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}



<style>
    @import url("https://fonts.googleapis.com/css2?family=Muli&display=swap");
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500&display=swap');

* {
  margin: 0;
  padding: 0;
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
}

body {
  font-family: "Muli", sans-serif;
}

.container-main{
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 88.2vh;
  padding-top: 100px;
  padding-bottom: 50px;
  /* overflow-y: scroll ; */
}

.mini-container{
  display:flex;
  width:100%;
  justify-content:space-between;
  padding:20px;
  box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
  border-radius:10px;
  margin-bottom: 20px;
}

.caption{
  /* margin-left:15px; */
  /* float:right; */
  font-family: 'Montserrat', sans-serif;
  font-weight:500;
}

.btn-photo{
  width:9rem;
  border:none;
  color:white;
  padding:10px;
  border-radius:12px;
}



@media only screen and (max-width: 650px) {
  .cross{
    position: absolute;
    right: 4rem;
    top: 6rem;
  }
}

</style>

<div class="container-main">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mini-container">
      <div class="together">
        <span class="caption">Edit Caption:</span>
        <br />
        {{form.caption}}
      </div>
    </div>
      <div style="display: flex;">
      <button class="btn-photo" style="background-color:dodgerblue;">Update Caption</button>
    </div> 
    </form>
</div>

<script>
 
</script>
    {% endblock %}

templates/events/search.html
{% extends "base.html" %}

{% block page_name %}
    Search
{% endblock page_name %}

{% block search-bar %}

{% endblock search-bar %}

{% block content %}

<style> 
    .input {
        width:100px;
    }
</style>

<div class="container" style=" padding-top: 80px;">
    <form method="get" action="{% url "events:search" %}">
        <div class="container">
            <div class="row">
            {% for field in form %} 
                <div class="col">
                    <label for="{{field.id_for_label}}">{{ field.html_name }} </label>
                    {{field}}
                </div>
            {% endfor %}
            </div>
        </div>
        <!-- {{form.as_p}} -->
        <div class="container" style="margin-top:20px;">
            <div class="row jrow justify-content-center">
                <div class="col">
                    <button type="submit" class= "btn btn-success">Submit</button>
                </div>
            </div>
        </div>
    </form>
</div>


<!-- <div style="padding-top:80px;">
    <form method="POST" action="{% url "events:search" %}">
        {% csrf_token %}
        <input type="text" name="city">
        <input type="text" name="address">
        <select type = "text" name = "event_type">
            {% for i in event_type %}
                <option value = "{{i}}" > {{i}} </option>
            {% endfor %}
        </select>
        <input type="number" name="price">
        <input type="submit" class="btn btn-success">
    </form>
</div>
-->

<div style="margin-bottom: 40px;">
    {% for event in events %}
        {% include 'partials/event_card.html' with event=event %}
    {% endfor %}
</div>

{% endblock %}
















{% comment %}
    {% block content %}
    <h2>Search</h2>
    
    <form method="get" action="{% url "events:search" %}">
        <div>
            <label for="address">Address</label>
            <input id="address" value="{{address}}" name="address" placeholder="Search by address" />
        </div>
        <div>
        <label for="city">City</label>
        <input id="city" value="{{s_city}}" name="city" placeholder="Search by city" />
        </div>
        <div>
            <label for="event_type">Event Type</label>
            <select name="event_type" id="event_type">
                <option value="0" {% if s_event_type == 0 %}selected{% endif %}>Random</option>
                {% for event_type in event_types %}
                    <option value="{{event_type.pk}}" {% if s_event_type == event_type.pk %}selected{% endif %}>{{event_type.name}}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="price">Price</label>
            <input value="{{price}}" type="number" name="price" id="price" placeholder="Price" />
        </div>
        <div>
            <label for="super_organizer">By Superorganizer Only?</label>
            <input type="checkbox" name="super_organizer" id="super_organizer" {% if super_organizer %}checked{% endif %}>
        </div>
        <button>Search</button>
    </form>

    <h2>Results:</h2>
    {% for event in events %}
        <h3>{{event}}</h3>
    {% endfor %}



{% endblock content %}
{% endcomment %}